{% set name = "apyxl" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apyxl-{{ version }}.tar.gz
  sha256: 05221c3eaf932c3af0078096af0fa97e482d5410a0f555854e34722972e23db6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy
    - pandas
    - xgboost >=2.0.0
    - scikit-learn
    - shap
    - hyperopt
    - matplotlib-base

test:
  imports:
    - apyxl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CyrilJl/apyxl
  summary: A Python package for data analysis and model optimization.
  description: The apyxl package (Another PYthon package for eXplainable Learning) is a simple wrapper around XGBoost, Hyperopt, and SHAP. It allows users to build high-performing regression or classification models and leverage SHAP analysis to gain insights into the relationships between inputs and outputs. With apyxl, processing categorical features, fitting models using Bayesian hyperparameter search, and creating SHAP explainers can all be done with a single line of code, streamlining the entire process from data preparation to model interpretation. Additionally, the package offers methods for time series normalization, with upcoming support for econometric tasks such as Difference-in-Differences and Regression Discontinuity.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
